apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingaccess
spec:
  replicas: 6
  template:
    spec:
      containers:
      - name: pingaccess
        resources:
          limits:
            memory: 2Gi
            cpu: 2
          requests:
            memory: 2Gi
            cpu: 2
