apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ds
spec:
  replicas: 6
  template:
    spec:
      containers:
        - name: ds
          resources:
            limits:
              memory: 12Gi
              cpu: 2
            requests:
              memory: 12Gi
              cpu: 2
          env:
          - name: MAX_HEAP_SIZE
            value: 12g
  volumeClaimTemplates:
    - spec:
        storageClassName: pingdirectory-io1
        resources:
          requests:
            storage: 250Gi