apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ds
spec:
  replicas: 6
  template:
    spec:
      containers:
        - name: ds
          resources:
            limits:
              memory: 12Gi
              cpu: 3
            requests:
              memory: 12Gi
              cpu: 3
          env:
          - name: MAX_HEAP_SIZE
            value: 12g
          - name: UNBOUNDID_JAVA_ARGS
            value: "-client -Xmx12g -Xms12g"
  volumeClaimTemplates:
    - spec:
        storageClassName: pingdirectory-io1
        resources:
          requests:
            storage: 250Gi