apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ds
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: ds
        resources:
          limits:
            memory: 30Gi
            cpu: 7
          requests:
            memory: 30Gi
            cpu: 7
        env:
        - name: MAX_HEAP_SIZE
          value: 30g
        - name: UNBOUNDID_JAVA_ARGS
          value: "-client -Xmx30g -Xms30g"
  volumeClaimTemplates:
  - metadata:
      name: out-dir
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: pingdirectory-io1
      resources:
        requests:
          storage: 1000Gi