apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ds
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: ds
        resources:
          limits:
            memory: 20Gi
            cpu: 3
          requests:
            memory: 20Gi
            cpu: 3
        env:
        - name: MAX_HEAP_SIZE
          value: 20g
        - name: UNBOUNDID_JAVA_ARGS
          value: "-client -Xmx20g -Xms20g"
  volumeClaimTemplates:
  - spec:
      storageClassName: pingdirectory-io1
      resources:
        requests:
          storage: 1000Gi