## Pipeline stages ##
stages:
  - build
  - test
  - chaos

## Global environment variables ##
variables:
  TENANT_DOMAIN: ping-aws.com

## Build stage ##
deploy:
  stage: build
  tags:
    - pd-eks-deploy
  image: docker.corp.pingidentity.com:5000/platform-pipeline/k8s-deploy-tools:stable
  script:
    - ./ci-scripts/build/deploy.sh
  except:
    - flux

## Test stage ##
pd-unit-tests:
  stage: test
  tags:
    - pd-eks-deploy
  image: docker.corp.pingidentity.com:5000/platform-pipeline/k8s-deploy-tools:stable
  script:
    - ./ci-scripts/test/run-test.sh pingdirectory
  except:
    - flux

pf-unit-tests:
  stage: test
  tags:
    - pd-eks-deploy
  image: docker.corp.pingidentity.com:5000/platform-pipeline/k8s-deploy-tools:stable
  script:
    - ./ci-scripts/test/run-test.sh pingfederate
  except:
    - flux

pa-unit-tests:
  stage: test
  tags:
    - pd-eks-deploy
  image: docker.corp.pingidentity.com:5000/platform-pipeline/k8s-deploy-tools:stable
  script:
    - ./ci-scripts/test/run-test.sh pingaccess
  except:
    - flux

integration-tests:
  stage: test
  tags:
    - pd-eks-deploy
  image: docker.corp.pingidentity.com:5000/platform-pipeline/k8s-deploy-tools:stable
  script:
    - ./ci-scripts/test/run-test.sh integration
  except:
    - flux

## Chaos testing stage ##
chaos-tests:
  stage: chaos
  tags:
    - pd-eks-deploy
  image: docker.corp.pingidentity.com:5000/platform-pipeline/k8s-deploy-tools:stable
  script:
    - ./ci-scripts/test/run-test.sh chaos
  except:
    - flux