# This defines the pingaccess deployment.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingaccess
spec:
  replicas: 1
  template:
    metadata:
      name: pingaccess
      annotations:
        lastUpdateReason: "NA"
    spec:
      containers:
      - name: pingaccess
        # FIXME: switch to stable image before GA
        image: pingidentity/pingaccess:5.3.1-edge
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1.5Gi"
            cpu: "1"
          limits:
            memory: "1.5Gi"
            cpu: "1"
        volumeMounts:
        - name: pingaccess-secrets
          mountPath: /opt/in/instance/conf
        readinessProbe:
          exec:
            command: [ liveness.sh ]
          periodSeconds: 30
          failureThreshold: 10
        livenessProbe:
          exec:
            command: [ liveness.sh ]
          periodSeconds: 30
          failureThreshold: 10
        ports:
        - containerPort: 9000
          name: pa-admin
        - containerPort: 443
          name: pa-runtime
        - containerPort: 3030
          name: pa-agent
        envFrom:
        - configMapRef:
            name: pingaccess-environment-variables
        - secretRef:
            name: devops-secret
            optional: true
      volumes:
      - name: pingaccess-secrets
        secret:
          secretName: pingaccess-secrets
          defaultMode: 256