# This defines the ingress for the pingaccess runtime service

# NOTE: it will only work if an ingress controller (e.g. nginx) is running on
# your cluster.

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pingaccess-ingress
  labels:
    role: pingaccess
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  tls:
  - hosts:
    - pingacess-dev.ping-demo.com
    - pingacessconsole-dev.ping-demo.com
    secretName: tls-secret
  rules:
  - host: pingacess-dev.ping-demo.com
    http:
      paths:
        # This rule gives external access to the pingaccess runtime service
        - path: /
          backend:
            serviceName: pingaccess
            servicePort: 443
  - host: pingacessconsole-dev.ping-demo.com
    http:
      paths:
        # This rule gives external access to the pingaccess console service
        - path: /
          backend:
            serviceName: pingaccess
            servicePort: 9000