kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- secret.yaml

commonLabels:
  role: pingaccess

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: pingaccess-environment-variables
  env: env_vars