apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pingfederate-passwords
data:
  PF_LDAP_PASSWORD: MkZlZGVyYXRlTTByZQ==

---

apiVersion: v1
kind: Secret
metadata:
  name: pingfederate-license
type: Opaque

---

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pingfederate-jwk
