apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ds
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: ds
        resources:
          limits:
            memory: 14Gi
            cpu: 3
          requests:
            memory: 14Gi
            cpu: 3
        env:
        - name: MAX_HEAP_SIZE
          value: 12g
        - name: UNBOUNDID_JAVA_ARGS
          value: "-client -Xmx12g -Xms12g"
  volumeClaimTemplates:
  - metadata:
      name: out-dir
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: pingdirectory-io1
      resources:
        requests:
          storage: 500Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pd-backup-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: pingdirectory-io1
  resources:
    requests:
      storage: 50Gi