apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ds
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: ds
          resources:
            limits:
              memory: 8g
            requests:
              memory: 8g