apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ds
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: ds
          resources:
            limits:
              memory: 8Gi
              cpu: 1
            requests:
              memory: 8Gi
              cpu: 1
          env:
          - name: MAX_HEAP_SIZE
            value: 8g
  volumeClaimTemplates:
    - spec:
        storageClassName: pingdirectory-gp2
        resources:
          requests:
            storage: 100Gi