apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingaccess-was
spec:
  template:
    spec:
      containers:
      - name: pingaccess-was
        resources:
          limits:
            memory: 2Gi
            cpu: 2
          requests:
            memory: 2Gi
            cpu: 2
