# This defines the passwords required for root users of pingdirectory (used by the backup cron job)

apiVersion: v1
kind: Secret
metadata:
  name: pingdirectory-passwords
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
type: Opaque
data:
  root-user-password: MkZlZGVyYXRlTTByZQ==
  admin-user-password: MkZlZGVyYXRlTTByZQ==
  encryption-password: MkZlZGVyYXRlTTByZQ==
  old-encryption-passwords: MkZlZGVyYXRlTTByZQ==
  encryption-settings.pin: MkZlZGVyYXRlTTByZQ==
  P14C_ENVIRONMENT_ID: YzNlMzczNTctNTA2Mi00MWJjLTk5NzItYTdlYTlkMTRhNWEy
  P14C_CLIENT_ID: ODkwNzM2NTQtNGVkMy00YTViLWI4OWMtZmY2YjVlMWI3ZDFi
  P14C_CLIENT_SECRET: UXA4aTAudHg4U3dVSWphdnlYWn5KYTZLQlA5SzN+azljTUYuUWF4UTZYclBvdHpmOU5DbFk2bHRLLjBJUU42MA==

---

apiVersion: v1
kind: Secret
metadata:
  name: pingdirectory-license
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
type: Opaque