kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

nameSuffix: -private

commonLabels:
  app.kubernetes.io/name: ingress-nginx
  app.kubernetes.io/part-of: ingress-nginx
  app.kubernetes.io/role: ingress-nginx-private

resources:
- configmap.yaml
- deployment.yaml
- service.yaml

vars:
- fieldref:
    fieldPath: metadata.name
  name: NGINX_CONFIGMAP_NAME_PRIVATE
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: nginx-configuration
- fieldref:
    fieldPath: metadata.name
  name: TCP_CONFIGMAP_NAME_PRIVATE
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: tcp-services
- fieldref:
    fieldPath: metadata.name
  name: UDP_CONFIGMAP_NAME_PRIVATE
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: udp-services
- fieldref:
    fieldPath: metadata.name
  name: SERVICE_NAME_PRIVATE
  objref:
    apiVersion: v1
    kind: Service
    name: ingress-nginx