kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- rbac.yaml
- secret.yaml
- configmap.yaml
- storage.yaml
- statefulset.yaml
- service.yaml
- periodic-backup.yaml

commonLabels:
  role: pingdirectory

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: pingdirectory-environment-variables
  envs:
  - env_vars

vars:
- name: K8S_STATEFUL_SET_NAME
  objref:
    kind: StatefulSet
    name: ds
    apiVersion: apps/v1