apiVersion: v1
kind: ServiceAccount
metadata:
  name: pd-serviceaccount

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: pd-role
rules:
  - apiGroups:
    - ""
    resources:
    - "pods"
    verbs:
    - get
  - apiGroups:
    - "apps"
    resources:
    - "statefulsets"
    verbs:
    - get
  - apiGroups:
    - ""
    resources:
    - "pods/exec"
    verbs:
    - create

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: pd-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pd-role
subjects:
  - kind: ServiceAccount
    name: pd-serviceaccount