# This defines the passwords required for root users of ds (used by the backup cron job)

apiVersion: v1
kind: Secret
metadata:
  name: pingdirectory-user-passwords
type: Opaque
data:
  root-user-password: MkZlZGVyYXRlTTByZQo=
  admin-user-password: MkZlZGVyYXRlTTByZQo=

---

apiVersion: v1
kind: Secret
metadata:
  name: pingdirectory-secrets
type: Opaque
# FIXME: remove the data section once the latest edge image is available
data:
  a-file: YW4gZXhhbXBsZSBmaWxlCg==