# This defines the deployment (as a stateful set) of the pingdirectory servers

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ds
spec:
  serviceName: pingdirectory
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      annotations:
        lastUpdateReason: "NA"
    spec:
      terminationGracePeriodSeconds: 300
      containers:
      - name: ds
        # FIXME: switch to stable image before GA
        image: pingidentity/pingdirectory:7.3.0.3-edge
        imagePullPolicy: Always
        ports:
        - containerPort: 389
          name: ldap
        - containerPort: 636
          name: ldaps
        resources:
          requests:
            memory: "5Gi"
            cpu: "2"
          limits:
            memory: "5Gi"
            cpu: "2"
        env:
        - name: K8S_STATEFUL_SET_NAME
          value: $(K8S_STATEFUL_SET_NAME)
        - name: K8S_STATEFUL_SET_SERVICE_NAME
          value: $(K8S_STATEFUL_SET_SERVICE_NAME)
        - name: MAX_HEAP_SIZE
          value: 4g
        - name: UNBOUNDID_JAVA_ARGS
          value: "-client -Xmx4g -Xms4g"
        # FIXME: fix home directory when containers run as non-root user
        - name: HOME
          value: /root
        envFrom:
        - configMapRef:
            name: pingdirectory-environment-variables
        - secretRef:
            name: devops-secret
            optional: true
        volumeMounts:
        - name: out-dir
          mountPath: /opt/out
        - name: passwords
          mountPath: /usr/local/secrets
          readOnly: true
        - name: pingdirectory-license
          mountPath: /opt/in/instance
          readOnly: true
        - name: ssh-id-key-secret
          mountPath: "$(HOME)/.ssh/id_rsa"
          readOnly: true
        - name: known-hosts-config
          mountPath: "$(HOME)/.ssh/known_hosts"
          readOnly: true
        readinessProbe:
          exec:
            command: [ liveness.sh ]
          periodSeconds: 30
          failureThreshold: 120
        livenessProbe:
          exec:
            command: [ liveness.sh ]
          initialDelaySeconds: 600
          periodSeconds: 30
          failureThreshold: 10
        lifecycle:
          preStop:
            exec:
              command:
              - /opt/staging/hooks/90-shutdown-sequence.sh
      volumes:
      - name: out-dir
        persistentVolumeClaim:
          claimName: out-dir
      - name: passwords
        secret:
          secretName: pingdirectory-passwords
          defaultMode: 0400
      - name: pingdirectory-license
        secret:
          secretName: pingdirectory-license
          optional: true
          defaultMode: 0400
      - name: ssh-id-key-secret
        secret:
          secretName: ssh-id-key-secret
          optional: true
          defaultMode: 0400
      - name: known-hosts-config
        configMap:
          name: known-hosts-config
          optional: true
          defaultMode: 0400
  volumeClaimTemplates:
  - metadata:
      name: out-dir
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: pingdirectory-gp2
      resources:
        requests:
          storage: 5Gi