apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: devops-secret

---

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pingcommon-passwords
data:
  PF_LDAP_PASSWORD: MkZlZGVyYXRlTTByZQ==

---

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ssh-id-key-secret