apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ds
spec:
  replicas: 12
  template:
    spec:
      containers:
        - name: ds
          resources:
            limits:
              memory: 16Gi
              cpu: 4
            requests:
              memory: 16Gi
              cpu: 4
          env:
          - name: MAX_HEAP_SIZE
            value: 16g
  volumeClaimTemplates:
    - spec:
        storageClassName: pingdirectory-io1
        resources:
          requests:
            storage: 500Gi