apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ds
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: ds
        resources:
          limits:
            memory: 62Gi
            cpu: 15
          requests:
            memory: 62Gi
            cpu: 15
        env:
        - name: MAX_HEAP_SIZE
          value: 62g
        - name: UNBOUNDID_JAVA_ARGS
          value: "-client -Xmx62g -Xms62g"
  volumeClaimTemplates:
  - spec:
      storageClassName: pingdirectory-io1
      resources:
        requests:
          storage: 2000Gi