apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ds
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: ds
        resources:
          limits:
            memory: 64Gi
            cpu: 15
          requests:
            memory: 64Gi
            cpu: 15
        env:
        - name: MAX_HEAP_SIZE
          value: 64g
        - name: UNBOUNDID_JAVA_ARGS
          value: "-client -Xmx64g -Xms64g"
  volumeClaimTemplates:
  - metadata:
      name: out-dir
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: pingdirectory-io1
      resources:
        requests:
          storage: 2000Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pd-backup-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: pingdirectory-io1
  resources:
    storage: 200Gi