---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: nri-prometheus
  namespace: newrelic
  labels:
    app.kubernetes.io/name: nri-prometheus
    helm.sh/chart: nri-prometheus-1.3.2
    app.kubernetes.io/instance: nri-bundle
    app.kubernetes.io/version: "2.2.0"
  annotations:
    null

---

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: nri-kube-events
    app.kubernetes.io/name: nri-kube-events
    helm.sh/chart: nri-kube-events-1.3.4
    app.kubernetes.io/instance: nri-bundle
    app.kubernetes.io/version: "1.3.0"
  name: nri-bundle-nri-kube-events
  namespace: newrelic
  annotations:
    null

---

apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: newrelic
  labels:
    app: newrelic-infrastructure
    chart: newrelic-infrastructure-1.6.2
    release: "nri-bundle"
  annotations:
    null

  name: nri-bundle-newrelic-infrastructure

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: nri-bundle-nri-metadata-injection
  namespace: newrelic
  labels:
    app.kubernetes.io/name: nri-metadata-injection
    helm.sh/chart: nri-metadata-injection-1.1.2
    app.kubernetes.io/instance: nri-bundle
    app.kubernetes.io/version: "1.3.0"

---

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: newrelic-logging
    chart: newrelic-logging-1.3.1
    release: "nri-bundle"
  name: nri-bundle-newrelic-logging
  namespace: newrelic

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: kube-state-metrics
    helm.sh/chart: kube-state-metrics-2.9.1
    app.kubernetes.io/instance: nri-bundle
  name: nri-bundle-kube-state-metrics
  namespace: newrelic
imagePullSecrets:
  []

