kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

configMapGenerator:
  - name: os-index-templates
    files:
      - healthchecks.json
      - backup-jobs.json
      - logstash.json
      - shrink-logstash.json
      - ingress-access.json
      - ingress-errors.json
      - pa-admin-audit.json
      - pa-admin-system.json
      - pa-api-audit.json
      - pa-audit.json
      - pa-engine-audit.json
      - pa-pingaccess.json
      - pd-access.json
      - pd-errors.json
      - pd-expensive-write-ops.json
      - pd-failed-ops.json
      - pd-replication.json
      - pd-server.json
      - pdg-access.json
      - pf-admin-api.json
      - pf-admin-log.json
      - pf-audit.json
      - pf-jvm-garbage-collection.json
      - pf-provisioner.json
      - pf-requests.json
      - pf-server.json
      - pf-transaction.json
      - general.json