apiVersion: v1
kind: Service
metadata:
  name: argocd-applicationset-controller
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"
    newrelic.io/scrape: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-metrics
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8082"
    newrelic.io/scrape: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-notifications-controller-metrics
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9001"
    newrelic.io/scrape: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-repo-server
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8084"
    newrelic.io/scrape: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-server-metrics
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8083"
    newrelic.io/scrape: "true"
---