# This defines the pingfederate deployment.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingfederate
spec:
  replicas: 1
  template:
    metadata:
      name: pingfederate
      annotations:
        lastUpdateReason: "NA"
    spec:
      containers:
      - name: pingfederate
        # FIXME: switch to stable image before GA
        image: pingidentity/pingfederate:9.3.1-edge
        imagePullPolicy: Always
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "1"
        volumeMounts:
        - name: pingfederate-license
          mountPath: /opt/in/instance/server/default/conf
          readOnly: true
        - name: ssh-id-key-secret
          mountPath: "$(HOME)/.ssh/id_rsa"
          readOnly: true
        - name: known-hosts-config
          mountPath: "$(HOME)/.ssh/known_hosts"
          readOnly: true
        readinessProbe:
          exec:
            command: [ liveness.sh ]
          periodSeconds: 30
          failureThreshold: 10
        livenessProbe:
          exec:
            command: [ liveness.sh ]
          periodSeconds: 30
          failureThreshold: 10
        ports:
        - containerPort: 9999
          name: pf-admin
        - containerPort: 9031
          name: pf-runtime
        env:
        # FIXME: fix home directory when containers run as non-root user
        - name: HOME
          value: /root
        envFrom:
        - configMapRef:
            name: pingfederate-environment-variables
        - secretRef:
            name: devops-secret
            optional: true
      volumes:
      - name: pingfederate-license
        secret:
          secretName: pingfederate-license
          optional: true
          defaultMode: 0400
      - name: ssh-id-key-secret
        secret:
          secretName: ssh-id-key-secret
          optional: true
          defaultMode: 0400
      - name: known-hosts-config
        configMap:
          name: known-hosts-config
          optional: true
          defaultMode: 0400