# This defines the ingress for the pingfederate authorization services.

# NOTE: it will only work if an ingress controller (e.g. nginx) is running on
# your cluster.

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pingfederate-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  tls:
  - hosts:
    - pingfederate-dev.ping-demo.com
    secretName: tls-secret
  rules:
  - host: pingfederate-dev.ping-demo.com
    http:
      paths:
      # This rule gives external access to the pingfederate AS endpoints
      - path: /
        backend:
          serviceName: pingfederate
          servicePort: 9031