apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alerting
  namespace: prometheus
data:
  provisioning.yaml: |
    contactPoints:
      - name: argo_webhook
        receivers:
          - uid: argo_webhook_1
            type: webhook
            settings:
              url: https://webhook.site/eeb6aaea-a691-459d-88e6-0e8e8a073b7c
    policies:
      - receiver: argo_webhook
        matchers:
          - severity =~ "warning|critical"
        group_wait: 30s
        group_internval: 5m
        repeat_interval: 4h
        routes:
          - receiver: argo_webhook
            matchers:
              - severity =~ "warning|critical"
    
    groups:
      - name: test1
        folder: test_group
        interval: 60s
        
        rules:
          - uid: my_id_1
            title: test_rule
            for: 60s
            labels:
              severity: critical
            annotations:
              summary: Pod {{ $labels.pod }} is not in running state
            condition: A
            data:
              - datasourceUid: prom0
                model:
                  conditions:
                  - evaluator:
                      params:
                      - 0
                      - 0
                      type: gt
                    operator:
                      type: and
                    query:
                      params: []
                    reducer:
                      params: []
                      type: max
                    type: query
                  datasource:
                    type: __expr__
                    uid: __expr__
                  expression: count(kube_pod_status_phase{namespace=~"ping-.*", job="kube-state-metrics",phase!="Running"}
                    == 1) by (pod, phase)
                  hide: false
                  intervalMs: 1000
                  maxDataPoints: 43200
                  refId: A
                  type: math
                queryType: ''
                refId: A
                relativeTimeRange:
                  from: 600
                  to: 0
