kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: prometheus

resources:
- namespace.yaml
- grafana.yaml
- prometheus.yaml
- grafana-dashboards.yaml

configMapGenerator:
- name: prometheus-environment-variables
  literals:
  - PROMETHEUS_RETENTION_TIME=15d
