apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: logstash-elastic
spec:
  minReplicas: 1
  maxReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: logstash-elastic
  metrics:
  - type: ContainerResource
    containerResource:
      container: logstash
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: ContainerResource
    containerResource:
      container: logstash
      name: mem
      target:
        type: Utilization
        averageUtilization: 90
