kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- https://github.com/fluxcd/flux/deploy?ref=master
- known-hosts-config.yaml

patchesStrategicMerge:
- patch-flux-deployment.yaml