apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux
  namespace: flux
spec:
  template:
    spec:
      containers:
      - name: flux
        args:
        - --git-url=git@github.com:pingidentity/ping-cloud-base.git
        - --git-path=k8s-configs/ping-cloud/test